### ISSUE TITLE
const RA_MASK seems incorrect

### ISSUE THREAD

**Issue by alex-lt-kong** [mwarning/SimpleDNS#13]
Hi mwarning,

It seems to me that the const RA_MASK's value defined here (https://github.com/mwarning/SimpleDNS/blob/f54b97f31056dc31e4650ceb52180a90144e4a02/main.c#L38) is incorrect. According to my understanding of the DNS protocol, the constant should be 0b0000000010000000 (or 0x80) instead of 0x8000 (or 0b1000000000000000).

**Comment by mwarning** [comment]
Good catch! Do you like to make a merge request?

**Comment by mwarning** [comment]
For reference: http://www.tcpipguide.com/free/t_DNSMessageHeaderandQuestionSectionFormat.htm

**Comment by mwarning** [comment]
I have added the fix, thank you.

**Comment by alex-lt-kong** [comment]
No problem--I should have opened a PR but since I am not too familiar with the protocol so I am not so sure lol.
