### ISSUE TITLE
On the implementation of decode_domain_name

### ISSUE THREAD

**Issue by alex-lt-kong** [mwarning/SimpleDNS#14]
Hi mwarning,

I am wondering why the follow section would work

[(https://github.com/mwarning/SimpleDNS/blob/5bdd512af5fa750fd55c28c7c04d74c40ae0ef2d/main.c#L339-L341)](https://github.com/mwarning/SimpleDNS/blob/5bdd512af5fa750fd55c28c7c04d74c40ae0ef2d/main.c#L339-L341)

Let's say the domain name in query is foo-bar.example.com, its encoded version is 7foo-bar6example3com0. Since the ASCII code of `-` is 45, which is not greater than 63, won't it be decoded to foo.bar.example.com by your current implementation?

( I do notice that you stated "No full validation is done!", but I am not sure if the issue I just point out is also expected)

Alex

**Comment by mwarning** [comment]
You are right. While decode_domain_name is meant to be simple in the first case, it could handle decoding much better with mininal changes.

**Comment by mwarning** [comment]
I have pushed a fix.

**Comment by alex-lt-kong** [comment]
lol I think the new implementation

https://github.com/mwarning/SimpleDNS/blob/a305b25c4b5f4b8e3fa9d432232b20f764d640d2/main.c#L339-L341

could greatly shrink the crack but it still suffers from similar issues. Suppose a domain name is
`www.this-is-a-domain-that-is-exactly-45-char-long.com`, its will be encoded to `3www45this-is-a-domain-that-is-exactly-45-char-long3com0`. Then the new implementation will parse it to `www-this-is-a-domain-that-is-exactly-45-char-long.com`.

But it appears to me that this is as far as your current approach can go--if we want to avoid this, we have to do it the "proper" way: re-writing the entire function to check the length prefix.

**Comment by mwarning** [comment]
yes, we would need a better implementation. If we can find something nicer that handles this better, then fine. Otherwise we can leave it, as it is not meant to be perfect.

**Comment by alex-lt-kong** [comment]
I thought about a different approach. For example, for 

https://github.com/mwarning/SimpleDNS/blob/a305b25c4b5f4b8e3fa9d432232b20f764d640d2/main.c#L157-L168

, write it to:

``` C
int get_A_Record(uint8_t addr[4], const char domain_name[])
{
  char records[] = {3, 'f', 'o', 'o', 3, 'b', 'a', 'r', 3, 'c', 'o', 'm', 0};
  if (strcmp(records, domain_name) == 0) {
    addr[0] = 1;
    addr[1] = 2;
    addr[2] = 3;
    addr[3] = 4;
    return 0;
  } else {
    return -1;
  }
}
```

The trick is that, we don't really encode/decode a domain name--we just compare if the encoded version is the same. By doing it this way, we `strcpy()` the domain name to `q->qName` and remove `encode_domain_name`/`decode_domain_name`, skipping the parsing altogether.

But yes I am aware that this repo is more or less for study/demonstration purpose, doing so may make the code less intuitive for a person learning the protocol (this is also how I found your repo in the first place!)--so this is an alternative approach for your reference.

**Comment by mwarning** [comment]
Sure, this would work. But personaly I find this too much of a shortcut :-)
