### ISSUE TITLE
Multi name server

### ISSUE THREAD

**Issue by hi-glenn** [mwarning/SimpleDNS#7]
There is more than one name server record generally.

For example:
ns1.foo.bar.
ns2.foo.bar.

How the name_server_record  struct support this condition ?

**Comment by mwarning** [comment]
SimpleDNS does not support that.

But A and AAAA queries are allowed to return multiple IP addresses as well. The SimpleDNS server only supports one response field for simplicity.

**Comment by hi-glenn** [comment]
Ok, I see.
