### ISSUE TITLE
I want to make multi answers, but encouter a problem.

### ISSUE THREAD

**Issue by hi-glenn** [mwarning/SimpleDNS#8]
Would you please have time to look at my code.

When I  `dig @127.0.0.1 -p 9000 foo.bar.com`  ,  only an answer returned.

At the same time, line 233 print pointer not nil,  however line 424 print poninter as (nil).

https://github.com/glennWang/SimpleDNS/blob/master/main.c#L233

**Comment by mwarning** [comment]
What is the behavior you expect?

For every question, only one answer is added. Multiple answers to one question are valid, but that is not what the code supports.

**Comment by hi-glenn** [comment]
The following is what I expect.

The answer has two record.

```
$ dig baidu.com A

; <<>> DiG 9.10.6 <<>> baidu.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54636
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;baidu.com.			IN	A

;; ANSWER SECTION:
baidu.com.		32	IN	A	39.156.69.79
baidu.com.		32	IN	A	220.181.38.148

;; Query time: 30 msec
;; SERVER: 10.0.0.1#53(10.0.0.1)
;; WHEN: Mon Jan 06 10:28:17 CST 2020
;; MSG SIZE  rcvd: 70
```

**Comment by mwarning** [comment]
The code in its current form adds one answer for each question. You would need to change the code to append multiple answers per each question contained in the request.

**Comment by hi-glenn** [comment]
https://github.com/mwarning/SimpleDNS/blob/master/main.c#L150

 As I understand, this line has mean that your code support multiple answers per each question.

**Comment by mwarning** [comment]
just multiple answers, but not per question. The change necessary is not that much, you probably just need to extend function resolver_process.
